name: lumina
description: "PortfolioApp"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.2.2

  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Almacenamiento local con Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # Gestión de estado
  provider: ^6.1.1

  # Skeleton screens y animaciones de carga
  shimmer: ^3.0.0

  # Gráficos para evolución del portafolio
  fl_chart: ^0.70.0

  # Trabajos en segundo plano
  workmanager: ^0.6.0

  # Cliente HTTP para llamadas a APIs
  http: ^0.13.5

  uuid: ^4.3.3

  # Iconos Lucide
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Generación de adaptadores Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # Generación automática de localización
  generate: true

flutter_native_splash:
  color: "#121212"
  image: assets/splash.png
  android: true
  ios: true
