name: lumina
description: "PortfolioApp"
publish_to: 'none'

version: 0.0.5+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1

  cupertino_icons: ^1.0.8



  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Almacenamiento local con Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_secure_storage: ^9.2.2

  # Gestión de estado
  provider: ^6.1.1

  # Skeleton screens y animaciones de carga
  shimmer: ^3.0.0

  # Gráficos para evolución del portafolio
  fl_chart: ^0.70.0

  # Trabajos en segundo plano
  workmanager: ^0.6.0

  # Cliente HTTP para llamadas a APIs
  http: ^1.4.0

  uuid: ^4.3.3

  # Iconos Lucide
  lucide_icons: ^0.257.0

  # SVG y URL Launcher
  flutter_svg: ^2.2.0
  url_launcher: ^6.2.4

  # Información del paquete
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Generación de adaptadores Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Generación automática de localización
  generate: true

  assets:
    - assets/images/coingecko_full_black.svg
    - assets/images/coingecko_full_white.svg
    - assets/images/coingecko_mono.svg
    - assets/images/coingecko_mono_logo.svg
    - assets/images/white_text_only.svg
    - assets/icons/
    - assets/logo/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#000000"
  image: assets/logo/lumina_splash.png
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true

  # ANDROID (unchanged)
  image_path_android: "assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.svg"

  # IOS (dedicated PNG)
  image_path_ios: "assets/icons/app_icon_ios_dark.png"
  remove_alpha_ios: true
