name: lumina
description: "PortfolioApp"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8

  # Internacionalización
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Almacenamiento local con Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2

  # Gestión de estado
  provider: ^6.1.1

  # Skeleton screens y animaciones de carga
  shimmer: ^3.0.0

  # Gráficos para evolución del portafolio
  fl_chart: ^0.70.0

  # Trabajos en segundo plano
  workmanager: ^0.6.0

  # Cliente HTTP para llamadas a APIs
  http: ^1.4.0

  uuid: ^4.3.3

  # Iconos Lucide
  lucide_icons: ^0.257.0

  # SVG y URL Launcher
  flutter_svg: ^2.2.0
  url_launcher: ^6.2.4

  # Export functionality
  share_plus: ^10.0.2

  # CSV import/export
  file_picker: ^8.0.6
  csv: ^6.0.0

  # Información del paquete
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Generación de adaptadores Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  # Splash & App Icons
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  # Generación automática de localización
  generate: true

  assets:
    - assets/images/coingecko_full_black.svg
    - assets/images/coingecko_full_white.svg
    - assets/images/coingecko_mono.svg
    - assets/images/coingecko_mono_logo.svg
    - assets/images/white_text_only.svg
    - assets/icons/
    - assets/logo/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400

# Splash screen: isotipo únicamente (Android e iOS)
flutter_native_splash:
  color: "#000000"
  color_dark: "#000000"

  # Imagen del isotipo
  image: assets/logo/splash_icon.png
  image_dark: assets/logo/splash_icon.png

  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android: true
  ios: true

  # Android 12+: también solo isotipo
  android_12:
    color: "#000000"
    color_dark: "#000000"
    image: assets/logo/splash_icon.png
    image_dark: assets/logo/splash_icon.png

# Iconos: Android adaptive + iOS estático
flutter_launcher_icons:
  android: true
  ios: true

  # ANDROID (adaptive): fondo negro + foreground transparente
  image_path_android: "assets/icons/app_icon_foreground.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  # (opcional para Android 13+) adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png"

  # iOS (PNG ya compuesto con fondo negro)
  image_path_ios: "assets/icons/app_icon.png"
  remove_alpha_ios: true
